language: java
notifications:
  email: false

script: "mvn -B clean install"

jobs:
  include:
  - stage: build
    os: linux
    name: precise
    dist: precise
    jdk: openjdk14
    sudo: false # faster builds
  - stage: build
    os: linux
    name: trusty
    dist: trusty
    jdk: openjdk14
    sudo: false # faster builds
